NumPy

In [1]:
import timeit
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from seaborn.external.husl import dot_product

feature_vector = np.array([5.1, 3.5, 1.4, 0.2, 5.0])

print(f'shape: {feature_vector.shape}')

data_matrix = np.array([[10, 20.0, 30],[40, 50, 60]])

print(f'Shape: {data_matrix.shape}')

shape: (5,)
Shape: (2, 3)


In [5]:
large_array = np.random.rand(100000)
python_list = large_array.tolist()

np_time = timeit.timeit('large_array * 2', globals={'large_array':large_array}, number=10)

def list_op(data):
    return [x *2 for x in data]
list_time = timeit.timeit('list_op(python_list)', globals={'list_op':list_op, 'python_list': python_list}, number=10)

print(f'Python: {list_time:.5f}')
print(f'Numpy: {np_time:.5f}')
print(f'NumPy is {list_time/np_time:.0f}x faster')




Python: 0.03335
Numpy: 0.00058
NumPy is 58x faster


In [7]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
dot_product = np.dot(v1, v2)
print(f'dot product :{dot_product}')
v1/2

dot product :32


array([0.5, 1. , 1.5])

In [11]:
matrix1 = np.array([[10,20,30],[40,50,60]])
matrix2 = np.array([[1,2,3],[4,5,6]])

mm = np.dot(matrix1, matrix2.T)
print(mm)


[[140 320]
 [320 770]]


In [13]:
np.random.rand(2,3,4)
np.random.rand(2,3)

array([[0.85768943, 0.12431004, 0.00222652],
       [0.70053212, 0.70697958, 0.40348565]])

In [15]:
from sklearn.datasets import load_iris
iris = load_iris(as_frame=True)

df_raw = iris.frame

In [17]:
df = df_raw.copy()

df.head()



sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0