# NumPy Basics

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4])
array = array * 2
print(array)
print(type(array))

## Multidimensional Arrays

In [ ]:
zero_dimen = np.array('a')
one_dimen = np.array(['a'])
two_dimen = np.array([[1, 2, 3], [1, 3, 4]])

array = np.array([
    [['A','B','C'],['D','E','F'],['G','H','I']],
    [['J','K','L'],['M','N','O'],['P','Q','R']],
    [['S','T','U'],['V','W','X'],['Y','Z','']]
])

print(zero_dimen.ndim, zero_dimen.shape)
print(one_dimen.ndim, one_dimen.shape)
print(two_dimen.ndim, two_dimen.shape)
print(array.ndim, array.shape)
print(array[0, 1, 2])
print(array[1, 1, 1])

In [ ]:
name = (
    array[2,0,0] +
    array[0,1,1] +
    array[0,0,0] +
    array[2,0,2] +
    array[1,1,0]
)
print(name)

## Slicing

In [ ]:
array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

print(array[0])
print(array[-1])
print(array[-2:, :2])

## Arithmetic Operations

In [ ]:
array = np.array([1, 2, 3])

print(array + 1)
print(array - 1)
print(array * 3)
print(array / 2)
print(array ** 2)

In [ ]:
array = np.array([1.01, 2.25, 3.99])

print(np.sqrt(array))
print(np.round(array))
print(np.ceil(array))
print(np.floor(array))
print(np.pi)

radii = np.array([1, 2, 3])
print(np.pi * radii ** 2)

## Element-wise Operations

In [ ]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)

## Comparison Operations

In [ ]:
scores = np.array([91, 55, 100, 73, 82, 64])

print(scores == 100)
print(scores > 80)
print(scores >= 80)

scores[scores <= 60] = 0
print(scores)

## Broadcasting

In [2]:
import numpy as np
array1 = np.array([[1, 2, 3, 4]])
array2 = np.array([[1], [2], [3], [4]])

print(array1.shape)
print(array2.shape)
print(array1 * array2)

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


Aggrgate Functions

In [8]:
import numpy as np

array = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(np.sum(array))
print(np.mean(array))
print(np.std(array))
print(np.var(array))
print(np.max(array))
print(np.min(array))
print(np.argmax(array))
print(np.argmin(array))
print(np.median(array))
print(np.percentile(array, 50))
print(np.sum(array, axis=0))


55
5.5
2.8722813232690143
8.25
10
1
9
0
5.5
5.5
[ 7  9 11 13 15]


Filtering

In [21]:
import numpy as np

ages = np.array([[25, 30, 35, 40, 45],[21,17,22,27,32]])

teenager = ages[ages < 18]

adults = ages[(ages > 22) & (ages < 40)]
seniors = ages[ages > 40]
evens = ages[ages%2 ==0]

ad = np.where(ages >= 18, ages, 0)

print(teenager)
print(adults)
print(seniors)
print(evens)
print(ad)


[17]
[25 30 35 27 32]
[45]
[30 40 22 32]
[[25 30 35 40 45]
 [21  0 22 27 32]]


Random Numbers

In [45]:
import numpy as np

rng = np.random.default_rng()
array = np.array([1,2,3,4,5,6,7,8,9,10])
rng.shuffle(array)
fruits = np.array(['apple', 'banana', 'cherry','orange','grapes'])
fruit =rng.choice(fruits, size=(3,3))
print(fruit)
print(rng.integers(1,7, (3,2)))
print(np.random.uniform(-1, 1, (3, 2)))
print(array)

[['orange' 'orange' 'orange']
 ['grapes' 'cherry' 'banana']
 ['cherry' 'cherry' 'orange']]
[[1 1]
 [2 1]
 [4 2]]
[[ 0.67203312 -0.07517593]
 [ 0.6317803   0.1559385 ]
 [ 0.23201708  0.42190149]]
[ 9  7  6  3 10  5  8  4  1  2]
